### ISSUE TITLE
Incompatibility with [Smart Minify]

### ISSUE THREAD

**Issue by alreShan** [emipa606/NaturesPrettySweet#2]
This decription is firstly write in WORD
URL: https://1drv.ms/w/s!Akhv5FMjQYoxhRDjbyU8hIi5EHVB

Incompatible mods:
[Smart Minify]#221028ver.
https://steamcommunity.com/sharedfiles/filedetails/?id=2815301242
[Nature's Pretty Sweet (Continued)]#230103ver.
https://steamcommunity.com/sharedfiles/filedetails/?id=2532618635

Test mod list (from RimPy) :
--------------------
[Mod list length: 11]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Visual Exceptions [https://steamcommunity.com/sharedfiles/filedetails/?id=2538411704]
Core [https:// no link (local mod)]
Better Log - Fix your errors with style [https://steamcommunity.com/sharedfiles/filedetails/?id=2772559481]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
Biotech [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
MinifyEverything [https://steamcommunity.com/sharedfiles/filedetails/?id=872762753]
Nature's Pretty Sweet (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2532618635]
Smart Minify [https://steamcommunity.com/sharedfiles/filedetails/?id=2815301242]
--------------------
Log URL:
https://gist.github.com/6dd3998cf009ff326822b70e0f452770

When you type something into search bar of stockpile filter,
Issue screenshot:
![图片](https://user-images.githubusercontent.com/104878767/212298418-2eb7c0be-29b0-47ec-ad66-4d4876aab8e5.png)

The issue can be fixed by load [Nature's Pretty Sweet (Continued)] after [Smart Minify]

The issue is NOT related with [Minify Everything]. I have tested it without loading [Smart Minify].
-------------------------

Screenshot just after game launched.
![图片](https://user-images.githubusercontent.com/104878767/212298441-d9f9b7f0-dd65-4322-bec2-c4968f0f155a.png)

Screenshot just after Dev.quicktest launched
![图片](https://user-images.githubusercontent.com/104878767/212298492-e80afa20-541c-409d-8cd4-e197197e5b9a.png)

Screenshot after type something in search bar.
![图片](https://user-images.githubusercontent.com/104878767/212298515-870070b1-6a46-4bb3-9fdb-103f933e75f5.png)

**Comment by emipa606** [comment]
Fixed in 2018aca
Thanks!
